# TV Script Generation

In this project, you'll generate your own [Seinfeld](https://en.wikipedia.org/wiki/Seinfeld) TV scripts using RNNs.  You'll be using part of the [Seinfeld dataset](https://www.kaggle.com/thec03u5/seinfeld-chronicles#scripts.csv) of scripts from 9 seasons.  The Neural Network you'll build will generate a new ,"fake" TV script, based on patterns it recognizes in this training data.

## Get the Data

The data is already provided for you in `./data/Seinfeld_Scripts.txt` and you're encouraged to open that file and look at the text. 
>* As a first step, we'll load in this data and look at some samples. 
* Then, you'll be tasked with defining and training an RNN to generate a new script!

In [1]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# load in data
import helper
data_dir = './data/Seinfeld_Scripts.txt'
text = helper.load_data(data_dir)

## Explore the Data
Play around with `view_line_range` to view different parts of the data. This will give you a sense of the data you'll be working with. You can see, for example, that it is all lowercase text, and each new line of dialogue is separated by a newline character `\n`.

In [2]:
view_line_range = (0, 10)

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import numpy as np

print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in text.split()})))

lines = text.split('\n')
print('Number of lines: {}'.format(len(lines)))
word_count_line = [len(line.split()) for line in lines]
print('Average number of words in each line: {}'.format(np.average(word_count_line)))

print()
print('The lines {} to {}:'.format(*view_line_range))
print('\n'.join(text.split('\n')[view_line_range[0]:view_line_range[1]]))

Dataset Stats
Roughly the number of unique words: 46367
Number of lines: 109233
Average number of words in each line: 5.544240293684143

The lines 0 to 10:
jerry: do you know what this is all about? do you know, why were here? to be out, this is out...and out is one of the single most enjoyable experiences of life. people...did you ever hear people talking about we should go out? this is what theyre talking about...this whole thing, were all out now, no one is home. not one person here is home, were all out! there are people trying to find us, they dont know where we are. (on an imaginary phone) did you ring?, i cant find him. where did he go? he didnt tell me where he was going. he must have gone out. you wanna go out you get ready, you pick out the clothes, right? you take the shower, you get all ready, get the cash, get your friends, the car, the spot, the reservation...then youre standing around, what do you do? you go we gotta be getting back. once youre out, you wanna get back! y

---
## Implement Pre-processing Functions
The first thing to do to any dataset is pre-processing.  Implement the following pre-processing functions below:
- Lookup Table
- Tokenize Punctuation

### Lookup Table
To create a word embedding, you first need to transform the words to ids.  In this function, create two dictionaries:
- Dictionary to go from the words to an id, we'll call `vocab_to_int`
- Dictionary to go from the id to word, we'll call `int_to_vocab`

Return these dictionaries in the following **tuple** `(vocab_to_int, int_to_vocab)`

In [3]:
import problem_unittests as tests

def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts (vocab_to_int, int_to_vocab)
    """
    # TODO: Implement Function
    vocab_to_int = dict()
    int_to_vocab = dict()
    
    id = 0
    for i in text:
        if i not in vocab_to_int.keys():
            vocab_to_int[i] = id
            id += 1
            
    for i,c in enumerate(vocab_to_int.keys()):
        int_to_vocab[i] = c        
    # return tuple
    return (vocab_to_int, int_to_vocab)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_create_lookup_tables(create_lookup_tables)

Tests Passed


### Tokenize Punctuation
We'll be splitting the script into a word array using spaces as delimiters.  However, punctuations like periods and exclamation marks can create multiple ids for the same word. For example, "bye" and "bye!" would generate two different word ids.

Implement the function `token_lookup` to return a dict that will be used to tokenize symbols like "!" into "||Exclamation_Mark||".  Create a dictionary for the following symbols where the symbol is the key and value is the token:
- Period ( **.** )
- Comma ( **,** )
- Quotation Mark ( **"** )
- Semicolon ( **;** )
- Exclamation mark ( **!** )
- Question mark ( **?** )
- Left Parentheses ( **(** )
- Right Parentheses ( **)** )
- Dash ( **-** )
- Return ( **\n** )

This dictionary will be used to tokenize the symbols and add the delimiter (space) around it.  This separates each symbols as its own word, making it easier for the neural network to predict the next word. Make sure you don't use a value that could be confused as a word; for example, instead of using the value "dash", try using something like "||dash||".

In [4]:
from string import punctuation

In [5]:
def token_lookup():
    """
    Generate a dict to turn punctuation into a token.
    :return: Tokenized dictionary where the key is the punctuation and the value is the token
    """
    # TODO: Implement Function
    symbols = ['.', ',', '"', ';', '!', '?', '(', ')', '-', '\n']
    token = ["||period||" , "||comma||" , "||quotationmark||" , "||semicolon||" , "||exclamation_mark||" , "||question_mark||" ,
            "||left_parentheses||" , "||right_parentheses||" , "||dash||" , "||return||"]
    return dict(zip(symbols, token))

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_tokenize(token_lookup)

Tests Passed


## Pre-process all the data and save it

Running the code cell below will pre-process all the data and save it to file. You're encouraged to lok at the code for `preprocess_and_save_data` in the `helpers.py` file to see what it's doing in detail, but you do not need to change this code.

In [6]:
data_dir

'./data/Seinfeld_Scripts.txt'

In [7]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# pre-process training data
helper.preprocess_and_save_data(data_dir, token_lookup, create_lookup_tables)

# Check Point
This is your first checkpoint. If you ever decide to come back to this notebook or have to restart the notebook, you can start from here. The preprocessed data has been saved to disk.

In [8]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper
import problem_unittests as tests

int_text, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()

In [9]:
len(int_text)

892110

## Build the Neural Network
In this section, you'll build the components necessary to build an RNN by implementing the RNN Module and forward and backpropagation functions.

### Check Access to GPU

In [10]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import torch

# Check for a GPU
train_on_gpu = torch.cuda.is_available()
if not train_on_gpu:
    print('No GPU found. Please use a GPU to train your neural network.')

## Input
Let's start with the preprocessed input data. We'll use [TensorDataset](http://pytorch.org/docs/master/data.html#torch.utils.data.TensorDataset) to provide a known format to our dataset; in combination with [DataLoader](http://pytorch.org/docs/master/data.html#torch.utils.data.DataLoader), it will handle batching, shuffling, and other dataset iteration functions.

You can create data with TensorDataset by passing in feature and target tensors. Then create a DataLoader as usual.
```
data = TensorDataset(feature_tensors, target_tensors)
data_loader = torch.utils.data.DataLoader(data, 
                                          batch_size=batch_size)
```

### Batching
Implement the `batch_data` function to batch `words` data into chunks of size `batch_size` using the `TensorDataset` and `DataLoader` classes.

>You can batch words using the DataLoader, but it will be up to you to create `feature_tensors` and `target_tensors` of the correct size and content for a given `sequence_length`.

For example, say we have these as input:
```
words = [1, 2, 3, 4, 5, 6, 7]
sequence_length = 4
```

Your first `feature_tensor` should contain the values:
```
[1, 2, 3, 4]
```
And the corresponding `target_tensor` should just be the next "word"/tokenized word value:
```
5
```
This should continue with the second `feature_tensor`, `target_tensor` being:
```
[2, 3, 4, 5]  # features
6             # target
```

In [11]:
words = np.array([1, 2, 3, 4, 5, 6, 7, 8 , 9 , 10 , 11 , 12 , 13])
sequence_length = 4

In [12]:
from torch.utils.data import TensorDataset, DataLoader
train_data = TensorDataset(torch.from_numpy(words), torch.from_numpy(words))

In [13]:
words

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
words[:sequence_length]

array([1, 2, 3, 4])

In [15]:
len(words)

13

In [16]:
len(words) - sequence_length

9

In [17]:
features = []
targets = []
print(f"Sample Text : {words}")
for i in range(len(words) - sequence_length):
    features.append(words[i : i+sequence_length])
    targets.append(words[i+sequence_length])
    print(f"Sequence {i+1} : {words[i : i+sequence_length]} Target : {words[i+sequence_length]}")

Sample Text : [ 1  2  3  4  5  6  7  8  9 10 11 12 13]
Sequence 1 : [1 2 3 4] Target : 5
Sequence 2 : [2 3 4 5] Target : 6
Sequence 3 : [3 4 5 6] Target : 7
Sequence 4 : [4 5 6 7] Target : 8
Sequence 5 : [5 6 7 8] Target : 9
Sequence 6 : [6 7 8 9] Target : 10
Sequence 7 : [ 7  8  9 10] Target : 11
Sequence 8 : [ 8  9 10 11] Target : 12
Sequence 9 : [ 9 10 11 12] Target : 13


In [18]:
from torch.utils.data import TensorDataset, DataLoader


def batch_data(words, sequence_length, batch_size):
    """
    Batch the neural network data using DataLoader
    :param words: The word ids of the TV scripts
    :param sequence_length: The sequence length of each batch
    :param batch_size: The size of each batch; the number of sequences in a batch
    :return: DataLoader with batched data
    """
    # TODO: Implement function
    ### Get maximum amount of sequences
    maxindex = len(words) - sequence_length
    ### Get the data
    features = []
    targets = []
    for i in range(len(words) - sequence_length):
        features.append(words[i : i+sequence_length])
        targets.append(words[i+sequence_length])
    ### Create Tensor Datasets
    dataset = TensorDataset(torch.from_numpy(np.array(features)), torch.from_numpy(np.array((targets))))
    data_loader = DataLoader(dataset, shuffle=True, batch_size=batch_size)
    return data_loader

# there is no test for this function, but you are encouraged to create
# print statements and tests of your own


### Test your dataloader 

You'll have to modify this code to test a batching function, but it should look fairly similar.

Below, we're generating some test text data and defining a dataloader using the function you defined, above. Then, we are getting some sample batch of inputs `sample_x` and targets `sample_y` from our dataloader.

Your code should return something like the following (likely in a different order, if you shuffled your data):

```
torch.Size([10, 5])
tensor([[ 28,  29,  30,  31,  32],
        [ 21,  22,  23,  24,  25],
        [ 17,  18,  19,  20,  21],
        [ 34,  35,  36,  37,  38],
        [ 11,  12,  13,  14,  15],
        [ 23,  24,  25,  26,  27],
        [  6,   7,   8,   9,  10],
        [ 38,  39,  40,  41,  42],
        [ 25,  26,  27,  28,  29],
        [  7,   8,   9,  10,  11]])

torch.Size([10])
tensor([ 33,  26,  22,  39,  16,  28,  11,  43,  30,  12])
```

### Sizes
Your sample_x should be of size `(batch_size, sequence_length)` or (10, 5) in this case and sample_y should just have one dimension: batch_size (10). 

### Values

You should also notice that the targets, sample_y, are the *next* value in the ordered test_text data. So, for an input sequence `[ 28,  29,  30,  31,  32]` that ends with the value `32`, the corresponding output should be `33`.

In [19]:
# test dataloader

test_text = range(50)
t_loader = batch_data(test_text, sequence_length=5, batch_size=10)

data_iter = iter(t_loader)
sample_x, sample_y = data_iter.next()

print(sample_x.shape)
print(sample_x)
print()
print(sample_y.shape)
print(sample_y)

torch.Size([10, 5])
tensor([[ 42,  43,  44,  45,  46],
        [ 22,  23,  24,  25,  26],
        [  1,   2,   3,   4,   5],
        [ 25,  26,  27,  28,  29],
        [  0,   1,   2,   3,   4],
        [ 17,  18,  19,  20,  21],
        [ 28,  29,  30,  31,  32],
        [ 10,  11,  12,  13,  14],
        [  7,   8,   9,  10,  11],
        [  3,   4,   5,   6,   7]])

torch.Size([10])
tensor([ 47,  27,   6,  30,   5,  22,  33,  15,  12,   8])


---
## Build the Neural Network
Implement an RNN using PyTorch's [Module class](http://pytorch.org/docs/master/nn.html#torch.nn.Module). You may choose to use a GRU or an LSTM. To complete the RNN, you'll have to implement the following functions for the class:
 - `__init__` - The initialize function. 
 - `init_hidden` - The initialization function for an LSTM/GRU hidden state
 - `forward` - Forward propagation function.
 
The initialize function should create the layers of the neural network and save them to the class. The forward propagation function will use these layers to run forward propagation and generate an output and a hidden state.

**The output of this model should be the *last* batch of word scores** after a complete sequence has been processed. That is, for each input sequence of words, we only want to output the word scores for a single, most likely, next word.

### Hints

1. Make sure to stack the outputs of the lstm to pass to your fully-connected layer, you can do this with `lstm_output = lstm_output.contiguous().view(-1, self.hidden_dim)`
2. You can get the last batch of word scores by shaping the output of the final, fully-connected layer like so:

```
# reshape into (batch_size, seq_length, output_size)
output = output.view(batch_size, -1, self.output_size)
# get last batch
out = output[:, -1]
```

# DEBUGGING

In [46]:
import torch.nn as nn

class RNN(nn.Module):
    
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, dropout=0.5):
        """
        Initialize the PyTorch RNN Module
        :param vocab_size: The number of input dimensions of the neural network (the size of the vocabulary)
        :param output_size: The number of output dimensions of the neural network
        :param embedding_dim: The size of embeddings, should you choose to use them        
        :param hidden_dim: The size of the hidden layer outputs
        :param dropout: dropout to add in between LSTM/GRU layers
        """
        super(RNN, self).__init__()
        # TODO: Implement function
        
        # set class variables
        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        self.embedding_dim = embedding_dim
        self.output_size = output_size
        # define model layers
        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, self.embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, 
                            dropout=dropout, batch_first=True)
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()    
    
    def forward(self, nn_input, hidden):
        """
        Forward propagation of the neural network
        :param nn_input: The input to the neural network
        :param hidden: The hidden state        
        :return: Two Tensors, the output of the neural network and the latest hidden state
        """
        # TODO: Implement function   
        batch_size = nn_input.size(0)
        print(f"NN Input Shape : {nn_input.shape}")
        print(f"Batch Size : {batch_size}")
        print(f"Embedding Dimension : {self.embedding_dim}")
        print(f"Hidden Dimension : {self.hidden_dim}")
        print(f"Output Dimension : {self.output_size}")
        # embeddings and lstm_out
        embeds = self.embedding(nn_input)
        print(f"Input Shape Afte Embedding Layer : {embeds.shape}")
        print("========================================================")
        lstm_out, hidden = self.lstm(embeds, hidden)
        print(f"Lstm Out Shape : {lstm_out.shape}")
        print(f"H_n Shape : {hidden[0].shape}")
        print(f"C_n Shape : {hidden[1].shape}")
        print("========================================================")
        print("First Último Output LSTM")
        print(lstm_out[0][2])
        print(f"H_n Última Capa Primer Elemento")
        print(f"{hidden[0][1][0]}")
        # stack up lstm outputs
        print("LSTM Output for First and Second Batch")
        print(lstm_out[0:2])
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        print("========================================================")     
        print(f"Stacking Outputs of LSTM Layer : {lstm_out.shape}")
        print(lstm_out[0:6])
        # dropout and fully-connected layer
        out = self.fc(lstm_out)
        print("========================================================")  
        print(f"After Fully Connected Layer {out.shape}")
        print(out)    
        # reshape to be batch_size first
        out = out.view(batch_size, -1, self.output_size)
        print(f"After Reshaping {out.shape}")
        print(out)
        out = out[:, -1] # get last batch of labels
        print(f"FC Final Output Last Batch : {out.shape}")
        print(out[:5])
        # return last sigmoid output and hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        '''
        Initialize the hidden state of an LSTM/GRU
        :param batch_size: The batch_size of the hidden state
        :return: hidden state of dims (n_layers, batch_size, hidden_dim)
        '''
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_rnn(RNN, train_on_gpu)

NN Input Shape : torch.Size([50, 3])
Batch Size : 50
Embedding Dimension : 15
Hidden Dimension : 10
Output Dimension : 20
Input Shape Afte Embedding Layer : torch.Size([50, 3, 15])
Lstm Out Shape : torch.Size([50, 3, 10])
H_n Shape : torch.Size([2, 50, 10])
C_n Shape : torch.Size([2, 50, 10])
First Último Output LSTM
tensor([ 0.0145,  0.1375,  0.0915, -0.0776,  0.0148,  0.0631,  0.1552,
        -0.1777,  0.1022, -0.1657], device='cuda:0')
H_n Última Capa Primer Elemento
tensor([ 0.0145,  0.1375,  0.0915, -0.0776,  0.0148,  0.0631,  0.1552,
        -0.1777,  0.1022, -0.1657], device='cuda:0')
LSTM Output for First and Second Batch
tensor([[[-0.0342,  0.0611,  0.0674, -0.0913,  0.0043,  0.0638,  0.0830,
          -0.0870,  0.0028, -0.0946],
         [-0.0734,  0.1125,  0.1066, -0.1254,  0.0384,  0.0750,  0.1203,
          -0.1110,  0.0415, -0.1267],
         [ 0.0145,  0.1375,  0.0915, -0.0776,  0.0148,  0.0631,  0.1552,
          -0.1777,  0.1022, -0.1657]],

        [[-0.0580,  0.0707,

### Define forward and backpropagation

Use the RNN class you implemented to apply forward and back propagation. This function will be called, iteratively, in the training loop as follows:
```
loss = forward_back_prop(decoder, decoder_optimizer, criterion, inp, target)
```

And it should return the average loss over a batch and the hidden state returned by a call to `RNN(inp, hidden)`. Recall that you can get this loss by computing it, as usual, and calling `loss.item()`.

**If a GPU is available, you should move your data to that GPU device, here.**

In [20]:
def forward_back_prop(rnn, optimizer, criterion, inp, target, hidden):
    """
    Forward and backward propagation on the neural network
    :param decoder: The PyTorch Module that holds the neural network
    :param decoder_optimizer: The PyTorch optimizer for the neural network
    :param criterion: The PyTorch loss function
    :param inp: A batch of input to the neural network
    :param target: The target output for the batch of input
    :return: The loss and the latest hidden state Tensor
    """
    
    # TODO: Implement Function
    
    # move data to GPU, if available
    if(train_on_gpu):
        inp, target = inp.cuda(), target.cuda()            
    # perform backpropagation and optimization
    hidden = tuple([each.data for each in hidden])

    # zero accumulated gradients
    rnn.zero_grad()   

    # get the output from the model
#     print(f"Input Shape : {inp.shape}")
#     print(f"Target Shape : {target.shape}")
    output, hidden = rnn(inp, hidden)
#     print(f"Output : {output.shape}")
#     print(f"Output : {output.squeeze().shape}")
#     print(f"Target : {target.shape}")
#     print(f"Hidden : {hidden[0].shape}")
#     print(output)
#     print(target)
    loss = criterion(output, target.long())
    loss.backward()
    optimizer.step()
    # return the loss over a batch and the hidden state produced by our model
    return loss.item(), hidden

# Note that these tests aren't completely extensive.
# they are here to act as general checks on the expected outputs of your functions
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_forward_back_prop(RNN, forward_back_prop, train_on_gpu)

Tests Passed


## Neural Network Training

With the structure of the network complete and data ready to be fed in the neural network, it's time to train it.

### Train Loop

The training loop is implemented for you in the `train_decoder` function. This function will train the network over all the batches for the number of epochs given. The model progress will be shown every number of batches. This number is set with the `show_every_n_batches` parameter. You'll set this parameter along with other parameters in the next section.

In [21]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""

def train_rnn(rnn, batch_size, optimizer, criterion, n_epochs, show_every_n_batches=100):
    batch_losses = []
    
    rnn.train()

    print("Training for %d epoch(s)..." % n_epochs)
    for epoch_i in range(1, n_epochs + 1):
        
        # initialize hidden state
        hidden = rnn.init_hidden(batch_size)
        
        for batch_i, (inputs, labels) in enumerate(train_loader, 1):
            
            # make sure you iterate over completely full batches, only
            n_batches = len(train_loader.dataset)//batch_size
            if(batch_i > n_batches):
                break
            
            # forward, back prop
            loss, hidden = forward_back_prop(rnn, optimizer, criterion, inputs, labels, hidden)          
            # record loss
            batch_losses.append(loss)

            # printing loss stats
            if batch_i % show_every_n_batches == 0:
                print('Epoch: {:>4}/{:<4}  Loss: {}\n'.format(
                    epoch_i, n_epochs, np.average(batch_losses)))
                batch_losses = []

    # returns a trained rnn
    return rnn

### Hyperparameters

Set and train the neural network with the following parameters:
- Set `sequence_length` to the length of a sequence.
- Set `batch_size` to the batch size.
- Set `num_epochs` to the number of epochs to train for.
- Set `learning_rate` to the learning rate for an Adam optimizer.
- Set `vocab_size` to the number of uniqe tokens in our vocabulary.
- Set `output_size` to the desired size of the output.
- Set `embedding_dim` to the embedding dimension; smaller than the vocab_size.
- Set `hidden_dim` to the hidden dimension of your RNN.
- Set `n_layers` to the number of layers/cells in your RNN.
- Set `show_every_n_batches` to the number of batches at which the neural network should print progress.

If the network isn't getting the desired results, tweak these parameters and/or the layers in the `RNN` class.

In [22]:
# Data params
# Sequence Length
sequence_length = 10  # of words in a sequence
# Batch Size
batch_size = 64

# data loader - do not change
train_loader = batch_data(int_text, sequence_length, batch_size)

In [23]:
# Training parameters
# Number of Epochs
num_epochs = 25
# Learning Rate
learning_rate = 0.001 

# Model parameters
# Vocab size
vocab_size = len(vocab_to_int)
# Output size
output_size = vocab_size
# Embedding Dimension
embedding_dim = 300
# Hidden Dimension
hidden_dim = 256
# Number of RNN Layers
n_layers = 2

# Show stats for every n number of batches
show_every_n_batches = 1000

### Train
In the next cell, you'll train the neural network on the pre-processed data.  If you have a hard time getting a good loss, you may consider changing your hyperparameters. In general, you may get better results with larger hidden and n_layer dimensions, but larger models take a longer time to train. 
> **You should aim for a loss less than 3.5.** 

You should also experiment with different sequence lengths, which determine the size of the long range dependencies that a model can learn.

In [24]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from workspace_utils import active_session

with active_session():
    # create model and move to gpu if available
    rnn = RNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers, dropout=0.5)
    if train_on_gpu:
        rnn.cuda()

    # defining loss and optimization functions for training
    optimizer = torch.optim.Adam(rnn.parameters(), lr=learning_rate)
    criterion = nn.CrossEntropyLoss()

    # training the model
    trained_rnn = train_rnn(rnn, batch_size, optimizer, criterion, num_epochs, show_every_n_batches)

    # saving the trained model
    helper.save_model('./save/trained_rnn', trained_rnn)
    print('Model Trained and Saved')

Training for 25 epoch(s)...
Epoch:    1/25    Loss: 5.290066518783569

Epoch:    1/25    Loss: 4.728915277719498

Epoch:    1/25    Loss: 4.551168636798859

Epoch:    1/25    Loss: 4.459713696479797

Epoch:    1/25    Loss: 4.347080304145813

Epoch:    1/25    Loss: 4.311201413631439

Epoch:    1/25    Loss: 4.279906487464904

Epoch:    1/25    Loss: 4.228494143486023

Epoch:    1/25    Loss: 4.222282981157303

Epoch:    1/25    Loss: 4.191772379875183

Epoch:    1/25    Loss: 4.144320255041122

Epoch:    1/25    Loss: 4.169014077425003

Epoch:    1/25    Loss: 4.15263531255722

Epoch:    2/25    Loss: 4.021310191476634

Epoch:    2/25    Loss: 3.9547448177337645

Epoch:    2/25    Loss: 3.955145547866821

Epoch:    2/25    Loss: 3.935763961315155

Epoch:    2/25    Loss: 3.9508822515010835

Epoch:    2/25    Loss: 3.9760567026138305

Epoch:    2/25    Loss: 3.9530919563770293

Epoch:    2/25    Loss: 3.9880911026000976

Epoch:    2/25    Loss: 3.968250494480133

Epoch:    2/25    Loss

/opt/conda/lib/python3.6/site-packages/torch/serialization.py:193: UserWarning: Couldn't retrieve source code for container of type RNN. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


Model Trained and Saved


### Question: How did you decide on your model hyperparameters? 
For example, did you try different sequence_lengths and find that one size made the model converge faster? What about your hidden_dim and n_layers; how did you decide on those?

**Answer:** Since the core of Machine Learning is to make a computer learn the way human do, I thought "how could I learn scripts?" A common dialogue doesn´t contain an extreme amount of words, otherwise, it becomes boring. That´s how I chose to use sequences of length 10. For the rest of the hyperparameters, I based my choices on the lessons and also considering the compute capability available. For example, I would´ve liked to use a larger embedding such as 400 or more layers, but it would´ve taken way too long to train. With the current hyperparameters, I managed to build a quite good dialogue.

---
# Checkpoint

After running the above training cell, your model will be saved by name, `trained_rnn`, and if you save your notebook progress, **you can pause here and come back to this code at another time**. You can resume your progress by running the next cell, which will load in our word:id dictionaries _and_ load in your saved model by name!

In [21]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import torch
import helper
import problem_unittests as tests

_, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()
trained_rnn = helper.load_model('./save/trained_rnn')

## Generate TV Script
With the network trained and saved, you'll use it to generate a new, "fake" Seinfeld TV script in this section.

### Generate Text
To generate the text, the network needs to start with a single word and repeat its predictions until it reaches a set length. You'll be using the `generate` function to do this. It takes a word id to start with, `prime_id`, and generates a set length of text, `predict_len`. Also note that it uses topk sampling to introduce some randomness in choosing the most likely next word, given an output set of word scores!

In [106]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import torch.nn.functional as F

def generate(rnn, prime_id, int_to_vocab, token_dict, pad_value, predict_len=100):
    """
    Generate text using the neural network
    :param decoder: The PyTorch Module that holds the trained neural network
    :param prime_id: The word id to start the first prediction
    :param int_to_vocab: Dict of word id keys to word values
    :param token_dict: Dict of puncuation tokens keys to puncuation values
    :param pad_value: The value used to pad a sequence
    :param predict_len: The length of text to generate
    :return: The generated text
    """
    rnn.eval()
    
    # create a sequence (batch_size=1) with the prime_id
    print(f"Initial Word Token for jerry: {prime_id}")
    print(f"Padding Token : {pad_value}")
    print(f"Padding Word : {int_to_vocab[pad_value]}")
    current_seq = np.full((1, sequence_length), pad_value)
    print(f"This is the Initial Empty Sequence {current_seq}")
    current_seq[-1][-1] = prime_id
    print(f"We set the initial token at the end : {current_seq}")
    predicted = [int_to_vocab[prime_id]]
    print(f"Initial Predicted Word : {predicted}")
    
    for _ in range(predict_len):
        if train_on_gpu:
            current_seq = torch.LongTensor(current_seq).cuda()
        else:
            current_seq = torch.LongTensor(current_seq)
        
        # initialize the hidden state
        hidden = rnn.init_hidden(current_seq.size(0))

        # get the output of the rnn
        output, _ = rnn(current_seq, hidden)
        print(f"The output is length of vocabulary : {output.shape}")
        # get the next word probabilities
        p = F.softmax(output, dim=1).data
        print(f"We apply softmax to convert to probability : {p.shape}")
        if(train_on_gpu):
            p = p.cpu() # move to cpu
         
        # use top_k sampling to get the index of the next word
        top_k = 5
        p, top_i = p.topk(top_k)
        print(f"After obtaining the probabilities we choose the top 5. We only care about the index : {top_i}")
        top_i = top_i.numpy().squeeze()
        
        # select the likely next word index with some element of randomness
        p = p.numpy().squeeze()
        word_i = np.random.choice(top_i, p=p/p.sum())
        print(f"We add Randomness on the top 5 words : {word_i} ")
        
        # retrieve that word from the dictionary
        word = int_to_vocab[word_i]
        predicted.append(word)
        print(f"We then search the selected word and transform it into text. Finally we append to predited : {predicted}")
        
        # the generated word becomes the next "current sequence" and the cycle can continue
        current_seq = np.roll(current_seq, -1, 1)
        current_seq[-1][-1] = word_i
        print(f"New Current Sequence : {current_seq}\n")
        print("===========END OF PREDICTION, STARTING NEW PREDICTION===================\n")
    
    gen_sentences = ' '.join(predicted)
    
    # Replace punctuation tokens
    for key, token in token_dict.items():
        ending = ' ' if key in ['\n', '(', '"'] else ''
        gen_sentences = gen_sentences.replace(' ' + token.lower(), key)
    gen_sentences = gen_sentences.replace('\n ', '\n')
    gen_sentences = gen_sentences.replace('( ', '(')
    
    # return all the sentences
    return gen_sentences

In [107]:
# run the cell multiple times to get different results!
gen_length = 3 # modify the length to your preference
prime_word = 'jerry' # name for starting the script

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
pad_word = helper.SPECIAL_WORDS['PADDING']
generated_script = generate(trained_rnn, vocab_to_int[prime_word + ':'], int_to_vocab, token_dict, vocab_to_int[pad_word], gen_length)
print(generated_script)

Initial Word Token for jerry: 101
Padding Token : 21387
Padding Word : <PAD>
This is the Initial Empty Sequence [[21387 21387 21387 21387]]
We set the initial token at the end : [[21387 21387 21387   101]]
Initial Predicted Word : ['jerry:']
The output is length of vocabulary : torch.Size([1, 21388])
We apply softmax to convert to probability : torch.Size([1, 21388])
After obtaining the probabilities we choose the top 5. We only care about the index : tensor([[  3611,   2570,   5354,   7734,  13346]])
We add Randomness on the top 5 words : 3611 
We then search the selected word and transform it into text. Finally we append to predited : ['jerry:', 'murderer']
New Current Sequence : [[21387 21387   101  3611]]

===========END OF PREDICTION, STARTING NEW PREDICTION===================

The output is length of vocabulary : torch.Size([1, 21388])
We apply softmax to convert to probability : torch.Size([1, 21388])
After obtaining the probabilities we choose the top 5. We only care about the 

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:53: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().


### Generate a New Script
It's time to generate the text. Set `gen_length` to the length of TV script you want to generate and set `prime_word` to one of the following to start the prediction:
- "jerry"
- "elaine"
- "george"
- "kramer"

You can set the prime word to _any word_ in our dictionary, but it's best to start with a name for generating a TV script. (You can also start with any other names you find in the original text file!)

In [108]:
vocab_to_int

{'this': 0,
 'is': 1,
 'out': 2,
 '||period||': 3,
 'and': 4,
 'one': 5,
 'of': 6,
 'the': 7,
 'single': 8,
 'most': 9,
 'enjoyable': 10,
 'experiences': 11,
 'life': 12,
 'people': 13,
 'did': 14,
 'you': 15,
 'ever': 16,
 'hear': 17,
 'talking': 18,
 'about': 19,
 'we': 20,
 'should': 21,
 'go': 22,
 '||question_mark||': 23,
 'what': 24,
 'theyre': 25,
 'whole': 26,
 'thing': 27,
 '||comma||': 28,
 'were': 29,
 'all': 30,
 'now': 31,
 'no': 32,
 'home': 33,
 'not': 34,
 'person': 35,
 'here': 36,
 '||exclamation_mark||': 37,
 'there': 38,
 'are': 39,
 'trying': 40,
 'to': 41,
 'find': 42,
 'us': 43,
 'they': 44,
 'dont': 45,
 'know': 46,
 'where': 47,
 '||left_parentheses||': 48,
 'on': 49,
 'an': 50,
 'imaginary': 51,
 'phone': 52,
 '||right_parentheses||': 53,
 'ring': 54,
 'i': 55,
 'cant': 56,
 'him': 57,
 'he': 58,
 'didnt': 59,
 'tell': 60,
 'me': 61,
 'was': 62,
 'going': 63,
 'must': 64,
 'have': 65,
 'gone': 66,
 'wanna': 67,
 'get': 68,
 'ready': 69,
 'pick': 70,
 'clothes'

In [27]:
# run the cell multiple times to get different results!
gen_length = 400 # modify the length to your preference
prime_word = 'jerry' # name for starting the script

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
pad_word = helper.SPECIAL_WORDS['PADDING']
generated_script = generate(trained_rnn, vocab_to_int[prime_word + ':'], int_to_vocab, token_dict, vocab_to_int[pad_word], gen_length)
print(generated_script)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:53: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().


jerry: saving the wheel.

kramer: oh yeah.(he stands up)

kramer:(to jerry) hey, you gotta get the car off the car.

george:(to jerry) hey, you know, you know, you know, i got the job and i jumped around..(to elaine) hey, i don't want to see you anymore.

george: you know what? you wanna do this?

kramer: yeah.

jerry: well, you know i think i should do this again.(to jerry) you know, i don't think so.

kramer: i don't want to see you.

elaine:(pointing at jerry) i think it's fate.

jerry:(pointing at her) no no no, i can't believe it.

jerry: i don't know.

george: i can't get out of here...

elaine:(pointing) i can't believe this!

jerry:(to elaine) hey, i gotta get the subway back.

jerry: oh, i don't know.

jerry: i can't believe you were giving it back.

kramer:(pointing at jerry) i was just wondering if i was a woman, i mean, the thing, they would like you.

elaine: well, that's not a good breakup.

elaine:(laughs slightly; coughing and pauses and coughing)

elaine: what do you m

#### Save your favorite scripts

Once you have a script that you like (or find interesting), save it to a text file!

In [28]:
# save script to a text file
f =  open("generated_script_1.txt","w")
f.write(generated_script)
f.close()

# The TV Script is Not Perfect
It's ok if the TV script doesn't make perfect sense. It should look like alternating lines of dialogue, here is one such example of a few generated lines.

### Example generated script

>jerry: what about me?
>
>jerry: i don't have to wait.
>
>kramer:(to the sales table)
>
>elaine:(to jerry) hey, look at this, i'm a good doctor.
>
>newman:(to elaine) you think i have no idea of this...
>
>elaine: oh, you better take the phone, and he was a little nervous.
>
>kramer:(to the phone) hey, hey, jerry, i don't want to be a little bit.(to kramer and jerry) you can't.
>
>jerry: oh, yeah. i don't even know, i know.
>
>jerry:(to the phone) oh, i know.
>
>kramer:(laughing) you know...(to jerry) you don't know.

You can see that there are multiple characters that say (somewhat) complete sentences, but it doesn't have to be perfect! It takes quite a while to get good results, and often, you'll have to use a smaller vocabulary (and discard uncommon words), or get more data.  The Seinfeld dataset is about 3.4 MB, which is big enough for our purposes; for script generation you'll want more than 1 MB of text, generally. 

# Submitting This Project
When submitting this project, make sure to run all the cells before saving the notebook. Save the notebook file as "dlnd_tv_script_generation.ipynb" and save another copy as an HTML file by clicking "File" -> "Download as.."->"html". Include the "helper.py" and "problem_unittests.py" files in your submission. Once you download these files, compress them into one zip file for submission.